server:
  port: "${SERVER_PORT:8080}"

logging.level:
  com.inditex: "DEBUG"

spring:
  sql.init.data-locations: "classpath:db/data/initial-data.sql"
  jpa.hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: "none"
  flyway:
    enabled: "true"
    locations: "db/schema"
  datasource:
    url: "jdbc:h2:mem:${DB_NAME:product-prices}"
    username: "${DB_USER:sa}"
    password: "${DB_PASSWORD:password}"
    driverClassName: "org.h2.Driver"
  h2.console:
    enabled: "${ENABLE_H2_CONSOLE:false}"
    path: "/h2-console"
    settings.web-allow-others: "true"

management:
  endpoints:
    enabled-by-default: "true"
    web:
      exposure:
        include : "*"
      base-path: "/metrics"
      path-mapping:
        metrics: "default-metrics"
        prometheus: "metrics"
  server.port: "${METRICS_PORT:8081}"
